title: ComputerVisionLab
description: Một lab thị giác máy tính vui vẻ ~~
theme: just-the-docs

url: https://just-the-docs.github.io


# Color scheme supports "light" (default) and "dark"
color_scheme: dark
